### model
model_name_or_path: /GLOBALFS/gznwp_3/qxj/shitianyuan/Model-Fusion/saves/model_fusion/FuseChat-Llama-3.2-3B-SFT/0409/openmathinstruct2_completion_dpo_iter_forward_1
# /GLOBALFS/gznwp_3/qxj/shitianyuan/Model-Fusion/saves/model_fusion/FuseChat-Llama-3.2-3B-SFT/0409/openmathinstruct2_completion_dpo_iter_forward_1
# /GLOBALFS/gznwp_3/qxj/models/FuseChat-Llama-3.2-3B-SFT
# /GLOBALFS/gznwp_3/qxj/shitianyuan/Model-Fusion/saves/model_fusion/FuseChat-Llama-3.2-3B-SFT/0409/openmathinstruct2_completion_dpo_iter_2
# /GLOBALFS/gznwp_3/qxj/models/FuseChat-Llama-3.2-3B-SFT
# /GLOBALFS/gznwp_3/qxj/yangzy/models/Llama-3.2-3B-Instruct
# /nas-wulanchabu/shitianyuan.sty/LLaMA-Factory/saves/model_fusion/Llama-3.2-3B-Instruct/0217/chosen_sft_iteration_2_from_base
# /nas-wulanchabu/shitianyuan.sty/LLaMA-Factory/saves/model_fusion/Llama-3.2-3B-Instruct/0103/stage1_sft
# /nas-wulanchabu/hongzhan.chz/tmp/models/meta-llama/Llama-3.2-3B-Instruct

### method
stage: completion_dpo #dpo completion_dpo
do_train: true
finetuning_type: full 
deepspeed: examples/deepspeed/ds_z3_config.json # ds_z3_offload_config ds_z3_config
pref_beta: 0.01

### dataset
dataset: model_fusion_dpo_completion
template: llama3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/model_fusion/FuseChat-Llama-3.2-3B-SFT/0409/openmathinstruct2_completion_dpo_iter_forward_2
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
save_only_model: true
seed: 42

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 100
